# Fly.io Configuration for SyncKairos v2.0
# Application name - update this for different environments
app = 'synckairos-staging'
primary_region = 'syd'  # Sydney, Australia (closest to New Zealand)

# Build configuration
[build]

# HTTP service configuration
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

# Health checks
[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/health'

# Ready check (validates Redis + PostgreSQL)
[[http_service.checks]]
  grace_period = '15s'
  interval = '60s'
  method = 'GET'
  timeout = '10s'
  path = '/ready'

# VM configuration
[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

# Environment variables (non-sensitive)
[env]
  NODE_ENV = 'production'
  PORT = '3000'
  LOG_LEVEL = 'info'

# Metrics configuration
[[metrics]]
  port = 3000
  path = '/metrics'

# Auto-scaling configuration
[scaling]
  min_machines = 2
  max_machines = 10

# Regions (add more as needed)
[regions]
  primary = 'syd'  # Sydney, Australia
  # secondary = ['sin', 'nrt']  # Singapore, Tokyo (uncomment for multi-region)
